algoritmo "ALGORITMO 1,1,13"
// Função :  DESENHO PINHEIRO
// Autor :  GELVAZIO
// Data : 09/10/2019
// Seção de Declarações 
var

inicio
// Seção de Comandos 
ESCREVAL("        X")
ESCREVAL("       XXX")
ESCREVAL("      XXXXX")
ESCREVAL("     XXXXXXX")
ESCREVAL("    XXXXXXXXX")
ESCREVAL("   XXXXXXXXXXX")
ESCREVAL("  XXXXXXXXXXXXX")
ESCREVAL(" XXXXXXXXXXXXXXX")
ESCREVAL("       XXX")
ESCREVAL("       XXX")
ESCREVAL("      XXXXX")
ESCREVAL("")
fimalgoritmo
