algoritmo "ALGORITMO DOIS NUMEROS O MENOR"
// Função :ESCREVA 2 NUMEROS E DIGA QUAL É O MENOR
// Autor :
// Data : 10/10/2019
// Seção de Declarações 
var
vA: INTEIRO
vB: INTEIRO

inicio
// Seção de Comandos 
ESCREVAL("ESCREVA O NUMERO DE A")
LEIA(vA)
ESCREVAL("ESCREVA O NUMERO DE B")
LEIA(vB)

SE (vA < vB) ENTAO
   ESCREVAL("O NUMERO MENOR É:",vA)
SENAO
    SE (vA > vB) ENTAO
       ESCREVAL("O NUMERO MENOR É:",vB)
    FIMSE
FIMSE

fimalgoritmo


