algoritmo "ALGORITMO 1,1,7"
// Função : TABELA
// Autor :   GELVAZIO
// Data : 09/10/2019
// Seção de Declarações 
var

inicio
// Seção de Comandos 
ESCREVAL("ALUNO (A)               NOTA")
ESCREVAL("========                ====")
ESCREVAL("ALINE                    9,0")
ESCREVAL("MÁRIO                    DEZ")
ESCREVAL("SÉRGIO                   4,5")
ESCREVAL("SHIRLEY                  7,0")
fimalgoritmo
