algoritmo "ALGORITMO NOVOS COM DOIS NUMEROS"
// Função : GELVAZIO
// Autor :
// Data : 10/10/2019
// Seção de Declarações 
var
vA: INTEIRO
vB: INTEIRO

inicio
// Seção de Comandos 
   ESCREVAL("ESCREVA O NUMERO DE A")
   LEIA(vA)
   ESCREVAL("ESCREVA O NUMERO DE B")
   LEIA(vB)
   
   SE (vA > vB) ENTAO
   ESCREVAL("O NUMERO MAIOR É:",vA)
   SENAO
   SE (vA < vB) ENTAO
   ESCREVAL ("O NUMERO MAIOR É:",vB)
   FIMSE
   
fimalgoritmo

