algoritmo "ALGORITMO 1,1,9"
// Função :  MONTAR X E L
// Autor :      GELVAZIO
// Data : 09/10/2019
// Seção de Declarações 
var

inicio
// Seção de Comandos 
ESCREVAL("L")
ESCREVAL("L")
ESCREVAL("L")
ESCREVAL("L")
ESCREVAL("L")
ESCREVAL("LLLLLL")
ESCREVAL("")
ESCREVAL("")
ESCREVAL("")
ESCREVAL("")
ESCREVAL("X    X")
ESCREVAL(" X  X")
ESCREVAL("  XX")
ESCREVAL(" X  X")
ESCREVAL("X    X")

fimalgoritmo
