algoritmo "ALGORITMO 1,1,8"
// Função : APRESENTACAO
// Autor :  GELVAZIO
// Data : 09/10/2019
// Seção de Declarações 
var

inicio
// Seção de Comandos 
ESCREVAL("*******    *********    *")
ESCREVAL("*          *       *    *")
ESCREVAL("*          *       *    *")
ESCREVAL("*******    *       *    *")
ESCREVAL("      *    *       *    *")
ESCREVAL("      *    *       *    *")
ESCREVAL("*******    *********    *******")
ESCREVAL("")

fimalgoritmo
