algoritmo "algoritmo 5"
// Função :  fazer algoritmo para somar 2 numeros
// Autor : Gelvazio
// Data : 08/10/2019
// Seção de Declarações 
var  // Variacao Nominal
vnome: literal
numero1: real
numero2: real
// Variavel de saida
vnumero: real



inicio
// Seção de Comandos 
Escreval("Escreva o numero 1")
Leia(numero1)
Escreval("escreva o numero 2")
Leia(numero2)
vNUmero:=(numero1+numero2)
Escreval (" a soma dos dois numeros é;",vnumero)
fimalgoritmo
