algoritmo "Meu nome"

var
      Nome: caractere
      N1, N2, S: INTEIRO
      M: REAL
      
inicio
ESCREVA ("DIGITE SEU NOME: ")
LEIA (NOME)

ESCREVAL ("MUITO PRAZER !!", NOME)




Nome <- "JESSICA"
ESCREVAL("MUITO PRAZER ", NOME)


ESCREVA("ME DIGA SEU NOME: ")
LEIA(NOME)

 ESCREVA ("ESCREVA UM NUMERO: ")
 LEIA(N1)
 ESCREVA ("ESCREVA OUTRO NUMERO: ")
 LEIA(N2)
 M <- (N1 + N2)/2
 ESCREVA("A MEDIA É ENTRE ",N1," E" ,N2, " É IGUAL A" , M )


fimalgoritmo
