-- MySQL Script generated by MySQL Workbench
-- 06/24/17 18:04:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema provafacildb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema provafacildb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provafacildb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `provafacildb` ;

-- -----------------------------------------------------
-- Table `provafacildb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`professor` (
  `proCodigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `proNome` VARCHAR(45) NOT NULL COMMENT '',
  `proEmail` VARCHAR(45) NOT NULL COMMENT '',
  `proSenha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`proCodigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`disciplina` (
  `disCodigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `disNome` VARCHAR(45) NOT NULL COMMENT '',
  `disAbreviacao` VARCHAR(5) NOT NULL COMMENT '',
  PRIMARY KEY (`disCodigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`tema` (
  `temCodigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `temNome` VARCHAR(45) NOT NULL COMMENT '',
  `tem_disCodigo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`temCodigo`)  COMMENT '',
  INDEX `fk_tema_disciplina1_idx` (`tem_disCodigo` ASC)  COMMENT '',
  CONSTRAINT `fk_tema_disciplina1`
    FOREIGN KEY (`tem_disCodigo`)
    REFERENCES `provafacildb`.`disciplina` (`disCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`questao` (
  `queCodigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `queEnunciado` TEXT NOT NULL COMMENT '',
  `que_temCodigo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`queCodigo`)  COMMENT '',
  INDEX `fk_questao_tema1_idx` (`que_temCodigo` ASC)  COMMENT '',
  CONSTRAINT `fk_questao_tema1`
    FOREIGN KEY (`que_temCodigo`)
    REFERENCES `provafacildb`.`tema` (`temCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`alternativa` (
  `altCodigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `altCorreta` TINYINT(1) NOT NULL COMMENT '',
  `alt_queCodigo` INT NOT NULL COMMENT '',
  `altText` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`altCodigo`)  COMMENT '',
  INDEX `fk_alternativa_questao1_idx` (`alt_queCodigo` ASC)  COMMENT '',
  CONSTRAINT `fk_alternativa_questao1`
    FOREIGN KEY (`alt_queCodigo`)
    REFERENCES `provafacildb`.`questao` (`queCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`curso` (
  `curCodigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `curNome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`curCodigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`professor_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`professor_curso` (
  `prf_proCodigo` INT NOT NULL COMMENT '',
  `prf_curCodigo` INT NOT NULL COMMENT '',
  INDEX `fk_professor_curso_professor1_idx` (`prf_proCodigo` ASC)  COMMENT '',
  CONSTRAINT `fk_professor_curso_professor1`
    FOREIGN KEY (`prf_proCodigo`)
    REFERENCES `provafacildb`.`professor` (`proCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professor_curso_curso1`
    FOREIGN KEY (`prf_curCodigo`)
    REFERENCES `provafacildb`.`curso` (`curCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provafacildb`.`curso_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provafacildb`.`curso_disciplina` (
  `cud_curCodigo` INT NOT NULL COMMENT '',
  `cud_disCodigo` INT NOT NULL COMMENT '',
  INDEX `fk_curso_disciplina_curNome1_idx` (`cud_curCodigo` ASC)  COMMENT '',
  INDEX `fk_curso_disciplina_disciplina1_idx` (`cud_disCodigo` ASC)  COMMENT '',
  CONSTRAINT `fk_curso_disciplina_curNome1`
    FOREIGN KEY (`cud_curCodigo`)
    REFERENCES `provafacildb`.`curso` (`curCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_curso_disciplina_disciplina1`
    FOREIGN KEY (`cud_disCodigo`)
    REFERENCES `provafacildb`.`disciplina` (`disCodigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `provafacildb`.`professor` (`proNome`, `proEmail`, `proSenha`) VALUES ('Saulo Vinícius', 'saulovinicius987@gmail.com', 'password');
INSERT INTO `provafacildb`.`professor` (`proNome`, `proEmail`, `proSenha`) VALUES ('Pedro Henrique', 'menezespedro10@hotmail.com', 'password');
INSERT INTO `provafacildb`.`professor` (`proNome`, `proEmail`, `proSenha`) VALUES ('Fernando Paim', 'fernando.lima@ifmg.edu.br', 'password');

INSERT INTO `provafacildb`.`curso` (`curNome`) VALUES ('Técnico Informática');
INSERT INTO `provafacildb`.`curso` (`curNome`) VALUES ('Tecnico Administração');
INSERT INTO `provafacildb`.`curso` (`curNome`) VALUES ('Ciência da Computação');
INSERT INTO `provafacildb`.`curso` (`curNome`) VALUES ('Engenharia Elétrica');
INSERT INTO `provafacildb`.`curso` (`curNome`) VALUES ('Marketing');

INSERT INTO `provafacildb`.`professor_curso` (`prf_proCodigo`, `prf_curCodigo`) VALUES ('3', '1');
INSERT INTO `provafacildb`.`professor_curso` (`prf_proCodigo`, `prf_curCodigo`) VALUES ('3', '3');
INSERT INTO `provafacildb`.`professor_curso` (`prf_proCodigo`, `prf_curCodigo`) VALUES ('1', '1');
INSERT INTO `provafacildb`.`professor_curso` (`prf_proCodigo`, `prf_curCodigo`) VALUES ('2', '1');

INSERT INTO `provafacildb`.`disciplina` (`disNome`, `disAbreviacao`) VALUES ('Programação Orientada a Objetos', 'POO');
INSERT INTO `provafacildb`.`disciplina` (`disNome`, `disAbreviacao`) VALUES ('Banco de Dados I', 'BDI');
INSERT INTO `provafacildb`.`disciplina` (`disNome`, `disAbreviacao`) VALUES ('Desenvolvimento Web II', 'DW II');
INSERT INTO `provafacildb`.`disciplina` (`disNome`, `disAbreviacao`) VALUES ('Desenvolvimento Móvel I', 'DM I');

INSERT INTO `provafacildb`.`curso_disciplina` (`cud_curCodigo`, `cud_disCodigo`) VALUES ('1', '1');
INSERT INTO `provafacildb`.`curso_disciplina` (`cud_curCodigo`, `cud_disCodigo`) VALUES ('1', '2');
INSERT INTO `provafacildb`.`curso_disciplina` (`cud_curCodigo`, `cud_disCodigo`) VALUES ('3', '3');
INSERT INTO `provafacildb`.`curso_disciplina` (`cud_curCodigo`, `cud_disCodigo`) VALUES ('1', '4');
INSERT INTO `provafacildb`.`curso_disciplina` (`cud_curCodigo`, `cud_disCodigo`) VALUES ('1', '3');

INSERT INTO `provafacildb`.`tema` (`temNome`, `tem_disCodigo`) VALUES ('Inserção no Banco de Dados', '2');
INSERT INTO `provafacildb`.`tema` (`temNome`, `tem_disCodigo`) VALUES ('Polimorfismo', '1');
INSERT INTO `provafacildb`.`tema` (`temNome`, `tem_disCodigo`) VALUES ('HTML', '3');
INSERT INTO `provafacildb`.`tema` (`temNome`, `tem_disCodigo`) VALUES ('Android', '4');

INSERT INTO `provafacildb`.`questao` (`queEnunciado`, `que_temCodigo`) VALUES ('Enunciado Questão POO Polimorfismo', '2');
INSERT INTO `provafacildb`.`questao` (`queEnunciado`, `que_temCodigo`) VALUES ('Enunciado Inserção no BD', '1');
INSERT INTO `provafacildb`.`questao` (`queEnunciado`, `que_temCodigo`) VALUES ('Enunciado de Web sobre HTML', '3');
INSERT INTO `provafacildb`.`questao` (`queEnunciado`, `que_temCodigo`) VALUES ('Enunciado de Android', '4');

INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('1', '1', 'Alternativa 1 sobre Polimorfismo');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '1', 'Alternativa 2 sobre Polimorfismo');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '1', 'Alternativa 3 sobre Polimorfismo');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '1', 'Alternativa 4 sobre Polimorfismo');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '2', 'Alternativa 1 sobre BD');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '2', 'Alternativa 2 sobre BD');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('1', '2', 'Alternativa 3 sobre BD');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '2', 'Alternativa 4 sobre BD');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '3', 'Alternativa 1 sobre HTML');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('1', '3', 'Alternativa 2 sobre HTML');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '3', 'Alternativa 3 sobre HTML');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '3', 'Alternativa 4 sobre HTML');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '4', 'Alternativa 1 sobre Android');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '4', 'Alternativa 2 sobre Android');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('0', '4', 'Alternativa 3 sobre Android');
INSERT INTO `provafacildb`.`alternativa` (`altCorreta`, `alt_queCodigo`, `altText`) VALUES ('1', '4', 'Alternativa 4 sobre Android');

