/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LocalizaEstado.java
 *
 * Created on 07/10/2011, 20:45:27
 */
package procura;


import controle.ItemDB;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Item;

/**
 *
 * @author Marciel
 */
public class LocalizaItem extends javax.swing.JInternalFrame {
    private JTextField campo;
    private JTextField campo1;

    public LocalizaItem(JTextField campo, JTextField campo1, JScrollPane jScrollPane1, JTable tbGrid) {
        this.campo = campo;
        this.campo1 = campo1;
        this.jScrollPane1 = jScrollPane1;
        this.tbGrid = tbGrid;
    }
    
  
    public LocalizaItem(JTextField campo,JTextField campo1) {
        initComponents();
        this.campo = campo;
        this.campo1 = campo1;
       
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código Produto");
        modelo.addColumn("Número Venda");
        
      
        ItemDB itemdb = new ItemDB();
        ArrayList<Item> itens = itemdb.getTodos();
        for (Item auxItem : itens){
            modelo.addRow(new Object[] {auxItem.getCodigoProduto(),auxItem.getNumeroVenda()});                        
        }        
        tbGrid.setModel(modelo);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbGrid = new javax.swing.JTable();

        setClosable(true);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGridMouseClicked
        // TODO add your handling code here:
        int linha = tbGrid.getSelectedRow();
        if (linha >= 0){
            String auxCodigo = tbGrid.getValueAt(linha, 0).toString();
            String auxNumeroVenda = tbGrid.getValueAt(linha,1).toString();
            campo.setText(auxCodigo);
            campo1.setText(auxNumeroVenda);
            
            
            
        }
    }//GEN-LAST:event_tbGridMouseClicked

private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jScrollPane1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbGrid;
    // End of variables declaration//GEN-END:variables
}
