/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadEstado.java
 *
 * Created on 05/08/2011, 14:31:42
 */
package view;

import controle.EstadoDB;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estado;

/**
 *
 * @author Marciel
 */
public class CadEstado extends javax.swing.JInternalFrame {

    /** Creates new form CadEstado */
    public CadEstado() {
        initComponents();
        atualizarTela(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BtnPrimeiro = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnProximo = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BtnNovo = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnGravar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        edtBusca = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbGrid = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EdtSigla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EdtNome = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        setTitle("Cadastro de Estado");

        BtnPrimeiro.setText("Primeiro");
        BtnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeiroActionPerformed(evt);
            }
        });

        BtnAnterior.setText("Anterior");
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });

        BtnProximo.setText("Próximo");
        BtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoActionPerformed(evt);
            }
        });

        BtnUltimo.setText("Último");
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });

        BtnAtualizar.setText("Atualizar");
        BtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnUltimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(BtnAtualizar)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrimeiro)
                    .addComponent(BtnAnterior)
                    .addComponent(BtnProximo)
                    .addComponent(BtnUltimo)
                    .addComponent(BtnAtualizar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BtnNovo.setText("Novo");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnGravar.setText("Gravar");
        BtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGravarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        edtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtBuscaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(BtnGravar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnGravar)
                    .addComponent(jLabel3)
                    .addComponent(edtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentResized(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TbGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbGridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbGrid);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registros", jPanel4);

        jLabel1.setText("Sigla");

        EdtSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtSiglaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        EdtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EdtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EdtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detalhes", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void atualizarTela(boolean verificaConsulta){
        JComboBox combo = new JComboBox();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Sigla");
        modelo.addColumn("Nome");        
        EstadoDB estadodb = new EstadoDB();
        ArrayList<Estado> estados = new ArrayList();
        if (verificaConsulta == true){
            estados = estadodb.getConsulta(edtBusca.getText());
        }else{
        estados = estadodb.getTodos();
        }
        for (Estado auxEstado : estados){
            modelo.addRow(new Object[] {auxEstado.getEst_sigla(),auxEstado.getNome()});            
            combo.addItem(auxEstado);
        }        
        TbGrid.setModel(modelo);
        int registros = TbGrid.getRowCount();
        if (registros > 0){
            TbGrid.setRowSelectionInterval(0, 0);
            Object auxSigla = TbGrid.getValueAt(0, 0);
            Object auxNome = TbGrid.getValueAt(0, 1);            
            EdtSigla.setText(auxSigla.toString());
            EdtNome.setText(auxNome.toString());  
        }     
        
    }
    
    private void BtnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeiroActionPerformed
        // TODO add your handling code here:
        int registros = TbGrid.getRowCount();
        if (registros > 0){
            TbGrid.setRowSelectionInterval(0, 0);
            Object auxSigla = TbGrid.getValueAt(0, 0);
            Object auxNome = TbGrid.getValueAt(0, 1);            
            EdtSigla.setText(auxSigla.toString());
            EdtNome.setText(auxNome.toString());
        }
    }//GEN-LAST:event_BtnPrimeiroActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        // TODO add your handling code here:
        int registros = TbGrid.getRowCount();
        if (registros > 0){
            int linhaSel = TbGrid.getSelectedRow();            
            int linha = linhaSel - 1;
            if (linha>=0){
                TbGrid.setRowSelectionInterval(linha, linha);
                Object auxSigla = TbGrid.getValueAt(linha, 0);
                Object auxNome = TbGrid.getValueAt(linha, 1);                
                EdtSigla.setText(auxSigla.toString());
                EdtNome.setText(auxNome.toString());  
            }
        }
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoActionPerformed
        // TODO add your handling code here:
        int registros = TbGrid.getRowCount();
        if (registros > 0){                       
            int linha = TbGrid.getSelectedRow()+1;
            int linhatotal = registros -1;
            if (linha>linhatotal){
                linha = linhatotal; 
            }
            TbGrid.setRowSelectionInterval(linha, linha);
            Object auxSigla = TbGrid.getValueAt(linha, 0);
            Object auxNome = TbGrid.getValueAt(linha, 1);            
            EdtSigla.setText(auxSigla.toString());
            EdtNome.setText(auxNome.toString());   
        }
    }//GEN-LAST:event_BtnProximoActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
        // TODO add your handling code here:
        int registros = TbGrid.getRowCount();
        if (registros > 0){
            int linha = registros -1; 
            TbGrid.setRowSelectionInterval(linha, linha);
            Object auxSigla = TbGrid.getValueAt(linha, 0);
            Object auxNome = TbGrid.getValueAt(linha, 1);            
            EdtSigla.setText(auxSigla.toString());
            EdtNome.setText(auxNome.toString());     
        }
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        EdtSigla.setText("");
        EdtNome.setText("");        
        EdtSigla.grabFocus();        
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        int resposta =  JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o registro?");
        if (resposta == JOptionPane.YES_OPTION){
            EstadoDB estadodb = new EstadoDB();
            String auxSigla = EdtSigla.getText();
            if (estadodb.excluirEstado(auxSigla)){
               JOptionPane.showMessageDialog(null,"Exclusão efetuada com sucesso!"); 
            }
            //JOptionPane.showMessageDialog(null,"Clicou em sim");
        }
        atualizarTela(false);
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGravarActionPerformed
        // TODO add your handling code here:                
        EstadoDB estadodb = new EstadoDB();
        String auxSigla = EdtSigla.getText();
        String auxNome = EdtNome.getText();        
        if (estadodb.getEstado(auxSigla)){
           //Alteração                       
           Estado estado = new Estado(auxSigla,auxNome);
           if (estadodb.alterarEstado(estado)){
              JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!"); 
           }else{
              JOptionPane.showMessageDialog(null,"Não foi possível efetuar a alteração!"); 
           }           
           atualizarTela(false);
        }else{
           //Inclusão             
           Estado estado = new Estado(auxSigla,auxNome);
           if (estadodb.inserirEstado(estado)){
              JOptionPane.showMessageDialog(null,"Inclusão realizada com sucesso!"); 
           }else{
              JOptionPane.showMessageDialog(null,"Não foi possível efetuar a inclusão!"); 
           } 
           atualizarTela(false);
        }
    }//GEN-LAST:event_BtnGravarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void TbGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbGridMouseClicked
        // TODO add your handling code here:
        int linha = TbGrid.getSelectedRow();
        if (linha >= 0){
            Object auxSigla = TbGrid.getValueAt(linha, 0);
            Object auxNome = TbGrid.getValueAt(linha, 1);            
            EdtSigla.setText(auxSigla.toString());
            EdtNome.setText(auxNome.toString());  
        }
    }//GEN-LAST:event_TbGridMouseClicked

    private void BtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarActionPerformed
        // TODO add your handling code here:
        atualizarTela(false);
    }//GEN-LAST:event_BtnAtualizarActionPerformed

private void edtBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtBuscaKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == 10){
        atualizarTela(true);
        
    }
}//GEN-LAST:event_edtBuscaKeyPressed

private void EdtSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtSiglaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EdtSiglaActionPerformed

private void EdtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtNomeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EdtNomeActionPerformed

private void jTabbedPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentResized
    // TODO add your handling code here:
}//GEN-LAST:event_jTabbedPane1ComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadEstado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnAtualizar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnGravar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPrimeiro;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JTextField EdtNome;
    private javax.swing.JTextField EdtSigla;
    private javax.swing.JTable TbGrid;
    private javax.swing.JTextField edtBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
